# Generated by Django 5.2 on 2025-06-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('tech', 'Technology'), ('other', 'Other')], default='music'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('hall_a', 'Hall A'), ('hall_b', 'Hall B'), ('johns_house', "John's House")], max_length=100),
        ),
    ]
